export const fruitsAndVegetables = [
  {
    "sku": "PROD-FV-001",
    "productName": "Organic Hass Avocados, Bag",
    "subCategory": "Fresh Fruit",
    "price": 5.99,
    "unit": "4 ct bag",
    "shortDescription": "Creamy, nutrient-dense avocados perfect for guacamole or toast.",
    "longDescription": "These California-grown Hass avocados are picked at the peak of freshness. Known for their high oil content and pebbly skin, they provide a rich, nutty flavor and a smooth texture that melts in your mouth.",
    "features": ["USDA Organic", "High in Healthy Fats", "Grown in California", "Pesticide-Free"],
    "inStock": true,
    "imagePrompt": "A bag of four green and black pebbly-skinned organic Hass avocados isolated on a clean white background, professional product photography."
  },
  {
    "sku": "PROD-FV-002",
    "productName": "Honeycrisp Apples",
    "subCategory": "Fresh Fruit",
    "price": 2.49,
    "unit": "per lb",
    "shortDescription": "Explosively crisp and sweet-tart apples for a perfect snack.",
    "longDescription": "Honeycrisp apples are celebrated for their exceptionally juicy and crisp texture. With a balanced sweetness and slight acidity, they are ideal for fresh eating, salads, or baking.",
    "features": ["Extra Crunchy", "Sweet and Tangy", "Versatile Culinary Use", "Local Harvest"],
    "inStock": true,
    "imagePrompt": "Two bright red Honeycrisp apples with slight yellow speckles, stem attached, isolated on a clean white background, high-resolution grocery photography."
  },
  {
    "sku": "PROD-FV-003",
    "productName": "Organic Baby Spinach, Container",
    "subCategory": "Leafy Greens",
    "price": 3.99,
    "unit": "5 oz container",
    "shortDescription": "Tender and pre-washed baby spinach leaves for easy meals.",
    "longDescription": "Our organic baby spinach is harvested early to ensure the most delicate leaves. Perfect for raw salads, smoothies, or a quick sauté, it's a nutritional powerhouse rich in iron and vitamins.",
    "features": ["Triple Washed", "USDA Organic", "Excellent Source of Vitamin K", "Freshness Guaranteed"],
    "inStock": true,
    "imagePrompt": "A clear plastic rectangular container filled with fresh, green organic baby spinach leaves, isolated on a clean white background."
  },
  {
    "sku": "PROD-FV-004",
    "productName": "Whole Seedless Watermelon",
    "subCategory": "Fresh Fruit",
    "price": 6.99,
    "unit": "each",
    "shortDescription": "Refreshing and sweet, the ultimate summer hydration.",
    "longDescription": "This seedless watermelon is bursting with sweet juice and a vibrant red interior. It’s the perfect centerpiece for picnics and gatherings, offering a refreshing low-calorie treat for everyone.",
    "features": ["Seedless Variety", "Immune-Boosting Vitamin C", "Hydrating and Low Calorie", "Farm-Fresh"],
    "inStock": true,
    "imagePrompt": "A large, oval whole green-striped seedless watermelon isolated on a clean white background, soft shadow."
  },
  {
    "sku": "PROD-FV-005",
    "productName": "Yellow Onions, Bag",
    "subCategory": "Root Vegetables",
    "price": 2.99,
    "unit": "3 lb bag",
    "shortDescription": "Essential cooking staple for savory depth and flavor.",
    "longDescription": "These versatile yellow onions provide a strong, pungent flavor that mellows and becomes sweet when cooked. They are the foundational ingredient for soups, stews, and roasts.",
    "features": ["Value Pack", "Long Shelf Life", "Great for Caramelizing", "Culinary Essential"],
    "inStock": true,
    "imagePrompt": "A mesh bag containing several golden-skin yellow onions, isolated on a clean white background, studio lighting."
  },
  {
    "sku": "PROD-FV-006",
    "productName": "Organic Bananas",
    "subCategory": "Fresh Fruit",
    "price": 0.89,
    "unit": "per lb",
    "shortDescription": "Naturally sweet and portable energy in every bite.",
    "longDescription": "Sourced from top organic farms, these bananas are allowed to ripen naturally for maximum flavor. They are the perfect snack for on-the-go or as a base for morning smoothies.",
    "features": ["USDA Organic", "Rich in Potassium", "Easy to Peel", "Sustainably Sourced"],
    "inStock": true,
    "imagePrompt": "A cluster of five bright yellow organic bananas with small green tips, isolated on a clean white background."
  },
  {
    "sku": "PROD-FV-007",
    "productName": "Broccoli Crowns",
    "subCategory": "Fresh Vegetables",
    "price": 1.79,
    "unit": "per lb",
    "shortDescription": "Fresh, tight green florets loaded with vitamins.",
    "longDescription": "Our broccoli crowns are selected for their firm stems and dense, dark green florets. They provide a satisfying crunch when raw and a tender, earthy flavor when steamed or roasted.",
    "features": ["High in Fiber", "Vibrant Green Florets", "Stalks Trimmed", "Antioxidant Rich"],
    "inStock": true,
    "imagePrompt": "Two fresh green broccoli crowns with thick stalks, showing tight florets, isolated on a clean white background."
  },
  {
    "sku": "PROD-FV-008",
    "productName": "Red Bell Peppers, 3-Pack",
    "subCategory": "Fresh Vegetables",
    "price": 4.49,
    "unit": "3 ct",
    "shortDescription": "Sweet, crunchy, and colorful additions to any dish.",
    "longDescription": "These red bell peppers are vine-ripened to achieve their signature sweetness and deep red color. They are perfect for snacking, stir-fries, or stuffing for a healthy dinner.",
    "features": ["Crisp Texture", "High in Vitamin A & C", "Convenient 3-Pack", "Vibrant Color"],
    "inStock": true,
    "imagePrompt": "Three glossy, deep red bell peppers with green stems, arranged neatly on a clean white background."
  },
  {
    "sku": "PROD-FV-009",
    "productName": "Organic Carrots, Bag",
    "subCategory": "Root Vegetables",
    "price": 1.99,
    "unit": "2 lb bag",
    "shortDescription": "Sweet and crunchy organic carrots for snacking and cooking.",
    "longDescription": "Our organic carrots are earth-grown and harvested for their natural sweetness. Whether you're slicing them for a crudité platter or roasting them for a side dish, they add color and nutrition.",
    "features": ["USDA Organic", "Beta-Carotene Rich", "Great for Juicing", "Farm-Fresh Quality"],
    "inStock": true,
    "imagePrompt": "A transparent bag of long, bright orange organic carrots, some with soil traces, isolated on a clean white background."
  },
  {
    "sku": "PROD-FV-010",
    "productName": "Blueberries, Large Pack",
    "subCategory": "Berries",
    "price": 4.99,
    "unit": "18 oz",
    "shortDescription": "Plump and sweet antioxidant superfood for the family.",
    "longDescription": "These blueberries are hand-picked at peak ripeness to ensure a sweet burst of flavor in every bite. They are perfect for topping yogurt, adding to muffins, or eating by the handful.",
    "features": ["Superfood Status", "Hand-Picked", "Resealable Container", "Sweet and Juicy"],
    "inStock": false,
    "imagePrompt": "A large clear plastic clamshell container filled with plump, dusty-blue fresh blueberries, isolated on a clean white background."
  },
  {
    "sku": "PROD-FV-011",
    "productName": "Russet Potatoes, Bag",
    "subCategory": "Root Vegetables",
    "price": 3.49,
    "unit": "5 lb bag",
    "shortDescription": "Fluffy and starchy, the ideal choice for baking and mashing.",
    "longDescription": "Known for their thick skin and high starch content, Russet potatoes are perfect for achieving that signature fluffy texture. They are the gold standard for baked potatoes and classic French fries.",
    "features": ["Starchy & Fluffy", "Value 5lb Bag", "Versatile Cooking", "Long Term Storage"],
    "inStock": true,
    "imagePrompt": "A brown paper bag partially showing several earthy, brown-skinned Russet potatoes, isolated on a clean white background."
  },
  {
    "sku": "PROD-FV-012",
    "productName": "English Seedless Cucumber",
    "subCategory": "Fresh Vegetables",
    "price": 1.50,
    "unit": "each",
    "shortDescription": "Mild and crisp cucumber with thin skin and no seeds.",
    "longDescription": "English cucumbers are prized for their thin, edible skin and lack of developed seeds. They offer a refreshing, slightly sweet crunch that is perfect for salads and sandwiches.",
    "features": ["Seedless Variety", "No Peeling Required", "Individually Wrapped", "Mild Flavor"],
    "inStock": true,
    "imagePrompt": "One long, thin English seedless cucumber wrapped in clear plastic film, isolated on a clean white background."
  },
  {
    "sku": "PROD-FV-013",
    "productName": "Organic Strawberries",
    "subCategory": "Berries",
    "price": 4.99,
    "unit": "1 lb",
    "shortDescription": "Luscious and sweet organic strawberries for a healthy treat.",
    "longDescription": "Grown under organic sunshine, these strawberries are exceptionally sweet and fragrant. Perfect for fruit salads, desserts, or dipping in dark chocolate for a special occasion.",
    "features": ["USDA Organic", "Deep Red Color", "Fragrant & Sweet", "Local Sustainable Farm"],
    "inStock": true,
    "imagePrompt": "A clear plastic pint container overflowing with bright red, heart-shaped organic strawberries with green caps, isolated on a white background."
  },
  {
    "sku": "PROD-FV-014",
    "productName": "Garlic, 3-Pack",
    "subCategory": "Root Vegetables",
    "price": 1.29,
    "unit": "3 ct",
    "shortDescription": "Pungent and aromatic bulbs to enhance every savory meal.",
    "longDescription": "Our white garlic bulbs feature large cloves with a bold, spicy flavor. An indispensable culinary staple, garlic adds depth to everything from pasta sauce to roasted meats.",
    "features": ["Large Cloves", "Bold Aroma", "Long Shelf Life", "Immune Support"],
    "inStock": true,
    "imagePrompt": "Three whole white garlic bulbs with dry papery skin, arranged in a small group, isolated on a white background."
  },
  {
    "sku": "PROD-FV-015",
    "productName": "Organic Kale, Bunch",
    "subCategory": "Leafy Greens",
    "price": 2.49,
    "unit": "each bunch",
    "shortDescription": "Nutrient-dense curly kale for salads and healthy chips.",
    "longDescription": "This organic green curly kale is a superfood favorite. Its sturdy leaves hold up well to dressings and are excellent when baked into crispy, seasoned kale chips.",
    "features": ["USDA Organic", "High in Vitamins A, C, K", "Curly Leaf Variety", "Robust Texture"],
    "inStock": true,
    "imagePrompt": "A large, vibrant bunch of organic green curly kale, tied with a rubber band, isolated on a clean white background."
  },
  {
    "sku": "PROD-FV-016",
    "productName": "Asparagus Spears",
    "subCategory": "Fresh Vegetables",
    "price": 3.99,
    "unit": "per lb",
    "shortDescription": "Tender and flavorful green spears for gourmet sides.",
    "longDescription": "Our asparagus is harvested at the peak of tenderness. These slender green spears offer an earthy, sophisticated flavor that is best highlighted by grilling, roasting, or steaming.",
    "features": ["Tender Tips", "Gourmet Quality", "High in Folate", "Freshly Harvested"],
    "inStock": true,
    "imagePrompt": "A bundle of fresh green asparagus spears with purple-tipped buds, held together by a blue rubber band, isolated on a white background."
  },
  {
    "sku": "PROD-FV-017",
    "productName": "Red Seedless Grapes",
    "subCategory": "Fresh Fruit",
    "price": 2.99,
    "unit": "per lb",
    "shortDescription": "Sweet and snappy table grapes for snacking.",
    "longDescription": "These red seedless grapes are known for their firm, snappy texture and reliable sweetness. They are the perfect addition to a cheese board or a child's lunchbox.",
    "features": ["Seedless convenience", "Snappy Texture", "Natural Sweetness", "Resveratrol Source"],
    "inStock": true,
    "imagePrompt": "A large bunch of plump, dusty-red seedless grapes on a green vine, isolated on a clean white background."
  },
  {
    "sku": "PROD-FV-018",
    "productName": "Roma Tomatoes",
    "subCategory": "Fresh Vegetables",
    "price": 1.49,
    "unit": "per lb",
    "shortDescription": "Meaty and flavorful tomatoes ideal for sauces and salsas.",
    "longDescription": "Roma tomatoes, also known as plum tomatoes, have a higher solids content and fewer seeds than other varieties. This makes them the perfect choice for thick, rich sauces and chunky salsas.",
    "features": ["Low Seed Content", "Meaty Texture", "Great for Cooking", "Vine-Ripened"],
    "inStock": true,
    "imagePrompt": "Four oval-shaped, deep red Roma tomatoes, arranged in a row, isolated on a clean white background."
  },
  {
    "sku": "PROD-FV-019",
    "productName": "Fresh Cauliflower",
    "subCategory": "Fresh Vegetables",
    "price": 3.49,
    "unit": "each",
    "shortDescription": "Versatile veggie perfect for ricing, roasting, or dipping.",
    "longDescription": "Our cauliflower heads are chosen for their snowy white curds and fresh green leaves. This versatile vegetable can be transformed into pizza crust, rice, or simply enjoyed as steaks.",
    "features": ["Snowy White Curds", "Low Carb Alternative", "High in Vitamin C", "Dense & Firm"],
    "inStock": true,
    "imagePrompt": "A whole head of fresh white cauliflower with outer green leaves partially intact, isolated on a white background."
  },
  {
    "sku": "PROD-FV-020",
    "productName": "Sweet Potatoes (Yams)",
    "subCategory": "Root Vegetables",
    "price": 1.25,
    "unit": "per lb",
    "shortDescription": "Sweet and creamy orange-fleshed tubers for roasting.",
    "longDescription": "These Garnet sweet potatoes feature a beautiful copper skin and deep orange flesh. They develop a rich, honey-like sweetness when roasted and provide a creamy texture for mashing.",
    "features": ["Excellent Beta-Carotene", "Naturally Sweet", "Garnet Variety", "Great for Baking"],
    "inStock": true,
    "imagePrompt": "Two large, oblong sweet potatoes with orange-copper skin and slight soil traces, isolated on a white background."
  },
  {
     "sku": "PROD-FV-021",
     "productName": "Dragon Fruit (Pitaya)",
     "subCategory": "Exotic Fruit",
     "price": 4.99,
     "unit": "each",
     "shortDescription": "Stunning exotic fruit with a mild sweetness and crunchy seeds.",
     "longDescription": "Pitaya, known for its vibrant pink skin and speckled white interior, is a tropical delight. Its texture is similar to kiwi, and its subtle flavor makes it a beautiful addition to smoothie bowls.",
     "features": ["Exotic & Unique", "High in Fiber", "Rich in Antioxidants", "Vibrant Presentation"],
     "inStock": true,
     "imagePrompt": "A whole vibrant pink dragon fruit with green-tipped scales, isolated on a clean white background, vibrant lighting."
  },
  {
     "sku": "PROD-FV-022",
     "productName": "Fresh Ginger Root",
     "subCategory": "Root Vegetables",
     "price": 3.99,
     "unit": "per lb",
     "shortDescription": "Zesty and aromatic root for teas, stir-fries, and baking.",
     "longDescription": "Our fresh ginger root provides a sharp, spicy kick and a warm aroma. It is a staple in Asian cuisine and is widely used for its soothing properties in teas and digestive health.",
     "features": ["Pungent & Spicy", "Natural Anti-inflammatory", "Great for Juicing", "Freshly Dug"],
     "inStock": true,
     "imagePrompt": "A large piece of branching, tan-colored fresh ginger root, isolated on a clean white background."
  },
  {
     "sku": "PROD-FV-023",
     "productName": "Organic Zucchini",
     "subCategory": "Fresh Vegetables",
     "price": 1.99,
     "unit": "per lb",
     "shortDescription": "Tender and versatile organic squash for any meal.",
     "longDescription": "These organic zucchinis are harvested while small and tender to ensure optimal flavor. They are perfect for spiralizing into 'zoodles', grilling, or adding to moist baked goods.",
     "features": ["USDA Organic", "Low Calorie", "Tender Edible Skin", "Quick Cooking"],
     "inStock": true,
     "imagePrompt": "Three sleek, dark green organic zucchinis with smooth skin, isolated on a white background."
  },
  {
     "sku": "PROD-FV-024",
     "productName": "Brussels Sprouts, Bag",
     "subCategory": "Fresh Vegetables",
     "price": 3.49,
     "unit": "1 lb bag",
     "shortDescription": "Tiny nutrient-packed cabbages perfect for roasting.",
     "longDescription": "Our Brussels sprouts are selected for their tight, bright green leaves. When roasted with olive oil and sea salt, they develop a deliciously crispy exterior and a sweet, nutty center.",
     "features": ["Nutty & Savory", "High in Vitamin K", "Uniform Sizing", "Convenient Mesh Bag"],
     "inStock": true,
     "imagePrompt": "A mesh bag filled with small, tight green Brussels sprouts, isolated on a clean white background."
  },
  {
     "sku": "PROD-FV-025",
     "productName": "Bartlett Pears",
     "subCategory": "Fresh Fruit",
     "price": 1.89,
     "unit": "per lb",
     "shortDescription": "Classic bell-shaped pear with a sweet and juicy bite.",
     "longDescription": "Bartlett pears are the classic choice for fresh eating and canning. As they ripen, their skin changes from green to yellow, signaling a buttery, juicy texture and intense sweetness.",
     "features": ["Juicy & Buttery", "Aromatic", "Ethylene-Ripened", "Good Source of Fiber"],
     "inStock": true,
     "imagePrompt": "Three yellow-green Bartlett pears, showing their classic bell shape, isolated on a clean white background."
  },
  {
     "sku": "PROD-FV-026",
     "productName": "Organic Celery Hearts",
     "subCategory": "Fresh Vegetables",
     "price": 2.99,
     "unit": "2 ct pack",
     "shortDescription": "Crisp and refreshing organic celery for snacks and soups.",
     "longDescription": "Our organic celery hearts are the most tender part of the plant. They offer a mild, salty crunch that's perfect for peanut butter snacks or as an aromatic base for your favorite recipes.",
     "features": ["USDA Organic", "Tender & Mild", "Pre-Trimmed", "Hydrating Snack"],
     "inStock": true,
     "imagePrompt": "A two-pack of organic celery hearts in a clear plastic sleeve, vibrant green color, isolated on white."
  },
  {
     "sku": "PROD-FV-027",
     "productName": "Gold Kiwifruit, 1 lb",
     "subCategory": "Exotic Fruit",
     "price": 5.49,
     "unit": "1 lb pack",
     "shortDescription": "Smooth-skinned Kiwi with a tropical gold interior.",
     "longDescription": "Unlike green kiwis, SunGold kiwifruit has a smooth, hairless skin and a vibrant gold flesh. It offers a sweeter, more tropical flavor profile and is even higher in Vitamin C.",
     "features": ["SunGold Variety", "Extra Sweet", "High Vitamin C", "Smooth Edible Skin"],
     "inStock": true,
     "imagePrompt": "Several smooth-skinned, oval gold kiwifruits, one sliced open to show the golden yellow interior, isolated on white."
  },
  {
     "sku": "PROD-FV-028",
     "productName": "Green Cabbage",
     "subCategory": "Fresh Vegetables",
     "price": 0.69,
     "unit": "per lb",
     "shortDescription": "Economical and versatile cabbage for slaws and stir-fry.",
     "longDescription": "Our green cabbage features heavy, dense heads with tightly packed leaves. It provides a satisfying crunch to slaw and ferments beautifully into homemade sauerkraut.",
     "features": ["Great Value", "Long Storage Life", "Crunchy Texture", "Rich in Vitamin C"],
     "inStock": true,
     "imagePrompt": "A whole, dense head of light green cabbage with outer waxy leaves, isolated on a white background."
  },
  {
     "sku": "PROD-FV-029",
     "productName": "Butternut Squash",
     "subCategory": "Fresh Vegetables",
     "price": 1.29,
     "unit": "per lb",
     "shortDescription": "Sweet and nutty winter squash for soups and roasting.",
     "longDescription": "This bell-shaped squash has a tan skin and a deep orange, sweet flesh. Once roasted, its texture becomes incredibly smooth, making it the perfect base for velvety autumn soups.",
     "features": ["Sweet & Nutty", "Smooth Texture", "High in Vitamin A", "Winter Staple"],
     "inStock": true,
     "imagePrompt": "A large tan-colored butternut squash with its characteristic pear shape, isolated on a white background."
  },
  {
     "sku": "PROD-FV-030",
     "productName": "Organic Blueberries",
     "subCategory": "Berries",
     "price": 5.99,
     "unit": "6 oz",
     "shortDescription": "Sweet and healthful organic berries grown without pesticides.",
     "longDescription": "Grown in harmony with nature, these organic blueberries are bursting with vitamins and antioxidants. Their sweet-tart balance makes them a superior topping for oats and pancakes.",
     "features": ["USDA Organic", "No Synthetic Pesticides", "Antioxidant Powerhouse", "Eco-Friendly Farming"],
     "inStock": true,
     "imagePrompt": "A small clear plastic container filled with dark purple organic blueberries, isolated on a white background."
  },
  {
     "sku": "PROD-FV-031",
     "productName": "Cilantro, Bunch",
     "subCategory": "Fresh Herbs",
     "price": 0.99,
     "unit": "each bunch",
     "shortDescription": "Fresh and aromatic herb for tacos, salsas, and curries.",
     "longDescription": "Our fresh cilantro bunches provide a bright, citrusy note to your cooking. Essential for Mexican and South Asian cuisines, use the leaves and stems to lift any recipe's flavor profile.",
     "features": ["Bright & Citrusy", "Culinary Essential", "Vibrant Green", "Hand-Bundled"],
     "inStock": true,
     "imagePrompt": "A lush bunch of fresh green cilantro with delicate leaves, tied together, isolated on a clean white background."
  },
  {
     "sku": "PROD-FV-032",
     "productName": "Jalapeño Peppers",
     "subCategory": "Fresh Vegetables",
     "price": 1.99,
     "unit": "per lb",
     "shortDescription": "Medium-heat peppers for a spicy kick in any dish.",
     "longDescription": "These Jalapeños offer a crisp texture and a manageable level of heat. Slice them for nachos, chop them for salsa, or stuff them with cream cheese for a crowd-pleasing appetizer.",
     "features": ["Versatile Heat", "Crisp Texture", "Deep Green Gloss", "Great for Pickling"],
     "inStock": true,
     "imagePrompt": "Five glossy deep green jalapeño peppers with small stems, isolated on a clean white background."
  },
  {
     "sku": "PROD-FV-033",
     "productName": "Blood Oranges, Bag",
     "subCategory": "Fresh Fruit",
     "price": 4.99,
     "unit": "2 lb bag",
     "shortDescription": "Unique citrus with a dramatic dark red interior and raspberry notes.",
     "longDescription": "Blood oranges are a seasonal treasure, prized for their deep crimson flesh. They offer a complex citrus flavor with distinct hints of raspberry, perfect for stunning juices and salads.",
     "features": ["Striking Red Flesh", "Raspberry-Citrus Flavor", "Seasonal Specialty", "High in Vitamin C"],
     "inStock": false,
     "imagePrompt": "A small group of blood oranges, one sliced in half to reveal its dramatic dark red interior, isolated on white."
  },
  {
     "sku": "PROD-FV-034",
     "productName": "Fresh Radishes, Bunch",
     "subCategory": "Fresh Vegetables",
     "price": 1.49,
     "unit": "each bunch",
     "shortDescription": "Peppery and crisp radishes for salads and snacking.",
     "longDescription": "Our radishes are harvested with their greens attached to ensure freshness. They provide a spicy, peppery crunch and a pop of bright red color to your fresh salads and tacos.",
     "features": ["Spicy & Crisp", "Vibrant Red Skin", "Greens Attached", "Low Calorie Crunch"],
     "inStock": true,
     "imagePrompt": "A bunch of six bright red round radishes with their long green leaves attached, isolated on a white background."
  },
  {
     "sku": "PROD-FV-035",
     "productName": "Organic Red Quinoa, Box",
     "subCategory": "Pantry Staples",
     "price": 4.99,
     "unit": "1 lb",
     "shortDescription": "Nutty and wholesome ancient grain with a vibrant red hue.",
     "longDescription": "Red quinoa maintains its shape better than white quinoa and offers a slightly heartier, nuttier flavor. It’s a complete protein source, making it the perfect base for nutritious grain bowls.",
     "features": ["USDA Organic", "Complete Protein", "Gluten-Free Grain", "Rich in Fiber"],
     "inStock": true,
     "imagePrompt": "A small cardboard box of red quinoa, with some grains visible, isolated on a white background."
  },
  {
     "sku": "PROD-FV-036",
     "productName": "Green Beans, Bag",
     "subCategory": "Fresh Vegetables",
     "price": 2.99,
     "unit": "12 oz bag",
     "shortDescription": "Stringless and tender green beans ready for steaming.",
     "longDescription": "These French-style green beans (haricots verts) are selected for their slender shape and tender texture. They are triple-washed and ready to be tossed into a pan with garlic and butter.",
     "features": ["Stringless Variety", "Pre-Washed", "Tender & Slender", "Ready to Cook"],
     "inStock": true,
     "imagePrompt": "A clear plastic bag containing many long, slender green beans, isolated on a white background."
  },
  {
     "sku": "PROD-FV-037",
     "productName": "Mango (Tommy Atkins)",
     "subCategory": "Exotic Fruit",
     "price": 1.25,
     "unit": "each",
     "shortDescription": "Tropical and sweet mango with a vibrant orange interior.",
     "longDescription": "The Tommy Atkins mango is a tropical favorite known for its wonderful aroma and sweet, juicy flesh. Perfect for eating fresh, adding to fruit salads, or blending into a creamy lassi.",
     "features": ["Tropical Aroma", "Naturally Sweet", "High in Vitamin A", "Grown in the Tropics"],
     "inStock": true,
     "imagePrompt": "A whole Tommy Atkins mango with green and red blush skin, isolated on a clean white background."
  },
  {
     "sku": "PROD-FV-038",
     "productName": "Red Cabbage",
     "subCategory": "Fresh Vegetables",
     "price": 0.89,
     "unit": "per lb",
     "shortDescription": "Vibrant and crunchy cabbage for colorful slaws and plating.",
     "longDescription": "Red cabbage offers a slightly earthier flavor than green cabbage and retains its beautiful purple hue when cooked. It is exceptionally high in antioxidants and adds visual pop to any dish.",
     "features": ["High in Antioxidants", "Bold Purple Color", "Lasting Freshness", "Crunchy Consistency"],
     "inStock": true,
     "imagePrompt": "A whole, dense head of purple-red cabbage with glossy tight leaves, isolated on a white background."
  },
  {
     "sku": "PROD-FV-039",
     "productName": "Organic Flat-Leaf Parsley",
     "subCategory": "Fresh Herbs",
     "price": 1.49,
     "unit": "each bunch",
     "shortDescription": "Robust and peppery organic parsley for seasoning and garnish.",
     "longDescription": "Also known as Italian parsley, this organic variety has a stronger, more peppery flavor than curly parsley. It’s an essential finishing touch for pasta, seafood, and roasted vegetables.",
     "features": ["USDA Organic", "Robust Aroma", "Deep Green Leaves", "Italian Variety"],
     "inStock": true,
     "imagePrompt": "A bundle of fresh organic flat-leaf Italian parsley, vibrant green and aromatic, isolated on white."
  },
  {
     "sku": "PROD-FV-040",
     "productName": "Sweet Corn, 4-Pack",
     "subCategory": "Fresh Vegetables",
     "price": 3.99,
     "unit": "4 ct pack",
     "shortDescription": "Golden and sweet corn on the cob, husks removed.",
     "longDescription": "Our sweet corn is harvested daily and shucked for your convenience. These golden kernels provide a sweet, milky burst of flavor that is synonymous with summer barbecues.",
     "features": ["Husked & Trimmed", "Extra Sweet Variety", "Great for Grilling", "Farm-Fresh Picked"],
     "inStock": true,
     "imagePrompt": "Four yellow corn on the cob pieces, husked and cleaned, arranged in a clear plastic tray, isolated on white."
  },
  {
     "sku": "PROD-FV-041",
     "productName": "Seedless Lemons, Bag",
     "subCategory": "Fresh Fruit",
     "price": 3.49,
     "unit": "1 lb bag",
     "shortDescription": "Tangy and juicy lemons without the annoyance of seeds.",
     "longDescription": "These innovative seedless lemons provide all the zesty flavor and juice you love without any seeds to fish out of your drinks or recipes. Perfect for baking and fresh lemonade.",
     "features": ["Completely Seedless", "Extra Juicy", "Great for Cooking", "Zesty Aroma"],
     "inStock": true,
     "imagePrompt": "A small mesh bag containing bright yellow seedless lemons, some showing their smooth skin, isolated on white."
  },
  {
     "sku": "PROD-FV-042",
     "productName": "Organic Spring Mix Salad",
     "subCategory": "Leafy Greens",
     "price": 4.49,
     "unit": "1 lb tub",
     "shortDescription": "Diverse medley of organic baby lettuces and greens.",
     "longDescription": "Our organic spring mix is a curated blend of tender baby lettuces, including chard, arugula, and radicchio. It offers a variety of textures and flavors for the perfect restaurant-style salad at home.",
     "features": ["USDA Organic", "Diverse Green Medley", "Pre-Washed & Ready", "Family Size Tub"],
     "inStock": true,
     "imagePrompt": "A large clear plastic tub filled with a colorful mix of small baby organic lettuce leaves, isolated on white."
  },
  {
     "sku": "PROD-FV-043",
     "productName": "Roma Crunch Lettuce",
     "subCategory": "Leafy Greens",
     "price": 2.99,
     "unit": "2 ct pack",
     "shortDescription": "The crunch of Romaine meeting the sweetness of Butter lettuce.",
     "longDescription": "Roma Crunch is a specialty lettuce variety that combines a sturdy Romaine texture with a sweet, mild flavor. It is the ideal vessel for lettuce wraps and stays crisp even with heavy dressings.",
     "features": ["Extra Crunchy", "Naturally Sweet", "Uniform Heads", "Perfect for Wraps"],
     "inStock": true,
     "imagePrompt": "Two heads of Roma crunch lettuce, showing a compact shape and light green leaves, isolated on white."
  },
  {
     "sku": "PROD-FV-044",
     "productName": "Organic Raspberries",
     "subCategory": "Berries",
     "price": 4.99,
     "unit": "6 oz",
     "shortDescription": "Delicate and tart organic raspberries for a refined treat.",
     "longDescription": "These organic raspberries are handled with extreme care to maintain their delicate structure. They offer a refined tartness and velvety texture that elevates any dessert or breakfast bowl.",
     "features": ["USDA Organic", "Fragile & Fresh", "Rich in Fiber", "Hand-Sorted"],
     "inStock": true,
     "imagePrompt": "A small clear plastic container filled with deep pink-red organic raspberries, isolated on a white background."
  },
  {
     "sku": "PROD-FV-045",
     "productName": "Green Bell Peppers",
     "subCategory": "Fresh Vegetables",
     "price": 0.89,
     "unit": "each",
     "shortDescription": "Versatile and crisp peppers for savory recipes and snacks.",
     "longDescription": "Our green bell peppers are harvested before they fully ripen, giving them a more robust, slightly bitter flavor that pairs perfectly with savory stir-fries and southwestern dishes.",
     "features": ["Crunchy & Savory", "Culinary Versatility", "Deep Green Color", "Low Calorie"],
     "inStock": true,
     "imagePrompt": "One large, glossy green bell pepper with a sturdy green stem, isolated on a clean white background."
  },
  {
     "sku": "PROD-FV-046",
     "productName": "Organic Leeks",
     "subCategory": "Fresh Vegetables",
     "price": 3.99,
     "unit": "2 ct bunch",
     "shortDescription": "Mild onion-flavored stalks for gourmet soups and braises.",
     "longDescription": "Organic leeks are a sophisticated member of the onion family. Their mild, creamy flavor is the hidden secret in classic French onion soup and many elegant vegetable tarts.",
     "features": ["USDA Organic", "Mild Onion Flavor", "Large Edible Stalks", "Freshly Harvested"],
     "inStock": true,
     "imagePrompt": "Two long organic leeks with white bases and fan-like dark green leaves, isolated on a clean white background."
  },
  {
     "sku": "PROD-FV-047",
     "productName": "Bosc Pears",
     "subCategory": "Fresh Fruit",
     "price": 1.99,
     "unit": "per lb",
     "shortDescription": "Elegant cinnamon-colored pear with a firm, spicy-sweet bite.",
     "longDescription": "Bosc pears are distinguished by their long necks and russeted, cinnamon-colored skin. Their firm texture makes them the supreme choice for poaching, as they hold their shape beautifully.",
     "features": ["Cinnamon Russet Skin", "Excellent for Poaching", "Spiced Nutty Flavor", "Elegant Shape"],
     "inStock": true,
     "imagePrompt": "Three long-necked, brown-skinned Bosc pears, showing their unique russet texture, isolated on white."
  },
  {
     "sku": "PROD-FV-048",
     "productName": "Organic Red Beets, Bunch",
     "subCategory": "Root Vegetables",
     "price": 2.99,
     "unit": "each bunch",
     "shortDescription": "Earthy and sweet organic beets with nutritious greens attached.",
     "longDescription": "Our organic red beets are valued for their deep crimson color and earthy sweetness. Don't throw away the leaves – they are highly nutritious and can be sautéed just like spinach.",
     "features": ["USDA Organic", "Iron-Rich Greens", "Deep Crimson Color", "Earthy & Sweet"],
     "inStock": true,
     "imagePrompt": "A bunch of three organic red beets with their vibrant green and purple-veined leaves still attached, isolated on white."
  },
  {
     "sku": "PROD-FV-049",
     "productName": "Papaya (Maradol)",
     "subCategory": "Exotic Fruit",
     "price": 1.19,
     "unit": "per lb",
     "shortDescription": "Large tropical fruit with a buttery texture and musky sweet flavor.",
     "longDescription": "Maradol papayas are prized for their consistent sweetness and large size. Their salmon-colored flesh is incredibly buttery and contains papain, an enzyme known for aiding digestion.",
     "features": ["Buttery Texture", "Digestive Enzymes", "Tropical Sweetness", "Vitamin C Rich"],
     "inStock": true,
     "imagePrompt": "A large Maradol papaya with yellow-green skin, isolated on a clean white background."
  },
  {
     "sku": "PROD-FV-050",
     "productName": "Organic Spaghetti Squash",
     "subCategory": "Fresh Vegetables",
     "price": 1.49,
     "unit": "per lb",
     "shortDescription": "Natural low-carb alternative that shreds into 'spaghetti'.",
     "longDescription": "This magic squash is a favorite for healthy eaters. Once cooked, the flesh can be shredded with a fork into long, noodle-like strands that pair perfectly with marinara sauce.",
     "features": ["USDA Organic", "Gluten-Free Pasta Alternative", "High in Vitamin A", "Fun for Kids"],
     "inStock": true,
     "imagePrompt": "A whole yellow oval spaghetti squash with a smooth skin, isolated on a white background."
  }
];
